export const Users = [
  {
    id: 1,
    profilePicture: 'person/1.jpeg',
    username: 'Lana Richards',
  },
  {
    id: 2,
    profilePicture: 'person/2.jpeg',
    username: 'Jason Wright',
  },
  {
    id: 3,
    profilePicture: 'person/3.jpeg',
    username: 'Jane Smith',
  },
  {
    id: 4,
    profilePicture: 'person/4.jpeg',
    username: 'Hanna Richardson',
  },
  {
    id: 5,
    profilePicture: 'person/5.jpeg',
    username: 'Kim Black',
  },
  {
    id: 6,
    profilePicture: 'person/6.jpeg',
    username: 'Tessa Grimm',
  },
  {
    id: 7,
    profilePicture: 'person/7.jpeg',
    username: 'Pablo Nueva',
  },
  {
    id: 8,
    profilePicture: 'person/8.jpeg',
    username: 'Clark Parker',
  },
  {
    id: 9,
    profilePicture: 'person/9.jpeg',
    username: 'Rosa James',
  },
  {
    id: 10,
    profilePicture: 'person/10.jpeg',
    username: 'Karen Novak',
  },
]

export const Posts = [
  {
    id: 1,
    desc: 'Yaay my first post.',
    photo: 'assets/post/1.jpeg',
    date: '5 mins ago',
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: 'assets/post/2.jpeg',
    date: '15 mins ago',
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: 'Enjiy life.',
    photo: 'assets/post/3.jpeg',
    date: '1 hour ago',
    userId: 3,
    like: 23,
    comment: 2,
  },
  {
    id: 4,
    photo: 'assets/post/4.jpeg',
    date: '4 hours ago',
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: 'assets/post/5.jpeg',
    date: '5 hours ago',
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: 'assets/post/6.jpeg',
    date: '1 day ago',
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: 'Testing, first time here',
    photo: 'assets/post/7.jpeg',
    date: '2 days ago',
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: 'assets/post/8.jpeg',
    date: '3 days ago',
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: 'No RegRAts.',
    photo: 'assets/post/9.jpeg',
    date: '5 days ago',
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: 'assets/post/10.jpeg',
    date: '1 week ago',
    userId: 10,
    like: 104,
    comment: 12,
  },
]
